export enum ECollection {
  ALLPRODUCT = 'ALLPRODUCT',
  BESTSELLER = 'BESTSELLER',
  NEWARRIVAL = 'NEWARRIVAL',
  LOWTOHIGH = 'LOWTOHIGH',
  HIGHTOLOW = 'HIGHTOLOW',
}

export enum EGender {
  MALE= 'MALE',
  FEMALE= 'FEMALE',
  OTHER = 'OTHER'
}