export enum ECollection {
  ALLPRODUCT = 'ALLPRODUCT',
  BESTSELLER = 'BESTSELLER',
  NEWARRIVAL = 'NEWARRIVAL',
  LOWTOHIGH = 'LOWTOHIGH',
  HIGHTOLOW = 'HIGHTOLOW',
}

export enum EGender {
  MALE= 'MALE',
  FEMALE= 'FEMALE',
  OTHER = 'OTHER'
}

export enum AuthBy {
  GOOGLE='GOOGLE',
  GITHUB='GITHUB',
  FACEBOOK='FACEBOOK',
  LOCAL='LOCAL'
}